# Generated by Django 5.1.2 on 2024-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_summary", "0002_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdf/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
